#############################
### Project configuration ###
#############################

# Indicate present working directory and metadata (sample) table

workdir: "/global/scratch/users/landen_gozashti/projects/Sperm_diversity/stacy_pipeline/analysis/20251205_sperm_trial/"
sample_table: "/global/scratch/users/landen_gozashti/projects/Sperm_diversity/stacy_pipeline/analysis/20251205_sperm_trial/config/pipelineConfigs/mouse_samples.tsv" # replace this with your actual sample table
my_tmp_path: "/global/scratch/users/landen_gozashti/resources/tmp"

# data is expected in the /global/path/to/hifi_dn_alu/data/ folder relative to the working directory
# to minimize issues with snakemake's wildcard parsing, use the structure below
fastq_basepath: "data/{specimen}/{lane}/{smrtcell}.fastq.gz"

##########################
### Path configuration ###
##########################

# Specify paths to scripts, packages, and other tools not managed by conda
# Working on helper functions for managing environmental $PATH as necessary.
SURVIVOR_path: "/global/scratch/users/landen_gozashti/tools/SURVIVOR/Debug"

###############################
### Analysis config options ###
###############################

# Indicate reference genome + annotation files (.bed, .gff, etc)
# The alias will be used for organizing mapping outputs:
# for example, output/alignment/CHM13 or output/alignment/hg38_no_alts

# Reference genome and annotations are expected in the default empty ./references directory.

reference:
  fasta: "/global/scratch/users/landen_gozashti/projects/Sperm_diversity/stacy_pipeline/analysis/20251205_sperm_trial/references/softmasked_clean.fa" # HGSVC hg38 no alts
  alias: "mouseT2T"
  annotations:
    repeats: "/global/scratch/users/landen_gozashti/projects/Sperm_diversity/stacy_pipeline/analysis/20251205_sperm_trial/references/simpleRepeats_clean_final.bed"

SURVIVOR_path: "/global/scratch/users/landen_gozashti/tools/SURVIVOR/Debug/"

longcall_path: "/global/scratch/users/landen_gozashti/tools/longcallD-v0.0.10_x64-linux/"

miniSV_path: "/global/scratch/users/landen_gozashti/tools/minisv/"

minimap2:
  readgroup: "@RG\\tID:{specimen}\\tSM:{specimen}\\tPL:PACBIO"

samtools:
  minQ: 10

sniffles:
  minsupport: 0
  mapq: 20
  mosaic-af-min: 0
  mosaic-af-max: 0.2
  mosaic-qc-strand: False

repeatmasker:
  species: "mouse"
  engine: "rmblast"
  custom_lib: "/global/scratch/users/landen_gozashti/projects/Sperm_diversity/stacy_pipeline/analysis/20251205_sperm_trial/references/TE_Library/famdb_curated.fa"
